# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'capture_c.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(751, 618)
        MainWindow.setMinimumSize(QtCore.QSize(751, 618))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/button/icons/Folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.treeView = QtWidgets.QTreeView(self.centralwidget)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_2.addWidget(self.treeView)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setMouseTracking(True)
        self.graphicsView.setWhatsThis("")
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_5 = QtWidgets.QAction(MainWindow)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(MainWindow)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(MainWindow)
        self.action_7.setObjectName("action_7")
        self.action_8 = QtWidgets.QAction(MainWindow)
        self.action_8.setObjectName("action_8")
        self.action_9 = QtWidgets.QAction(MainWindow)
        self.action_9.setObjectName("action_9")
        self.action_I = QtWidgets.QAction(MainWindow)
        self.action_I.setObjectName("action_I")
        self.action_R = QtWidgets.QAction(MainWindow)
        self.action_R.setObjectName("action_R")
        self.action_Q = QtWidgets.QAction(MainWindow)
        self.action_Q.setObjectName("action_Q")
        self.action_G = QtWidgets.QAction(MainWindow)
        self.action_G.setObjectName("action_G")
        self.action_13 = QtWidgets.QAction(MainWindow)
        self.action_13.setObjectName("action_13")
        self.action_14 = QtWidgets.QAction(MainWindow)
        self.action_14.setObjectName("action_14")
        self.action_15 = QtWidgets.QAction(MainWindow)
        self.action_15.setObjectName("action_15")
        self.action_16 = QtWidgets.QAction(MainWindow)
        self.action_16.setObjectName("action_16")
        self.action1pt = QtWidgets.QAction(MainWindow)
        self.action1pt.setCheckable(True)
        self.action1pt.setChecked(True)
        self.action1pt.setObjectName("action1pt")
        self.action2pt = QtWidgets.QAction(MainWindow)
        self.action2pt.setCheckable(True)
        self.action2pt.setObjectName("action2pt")
        self.action3pt = QtWidgets.QAction(MainWindow)
        self.action3pt.setCheckable(True)
        self.action3pt.setObjectName("action3pt")
        self.action4pt = QtWidgets.QAction(MainWindow)
        self.action4pt.setCheckable(True)
        self.action4pt.setObjectName("action4pt")
        self.action5pt = QtWidgets.QAction(MainWindow)
        self.action5pt.setCheckable(True)
        self.action5pt.setObjectName("action5pt")
        self.action6pt = QtWidgets.QAction(MainWindow)
        self.action6pt.setCheckable(True)
        self.action6pt.setObjectName("action6pt")
        self.action_17 = QtWidgets.QAction(MainWindow)
        self.action_17.setObjectName("action_17")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CaptureEdit"))
        self.label.setText(_translate("MainWindow", "파일경로"))
        self.label_2.setText(_translate("MainWindow", "파일이름"))
        self.action.setText(_translate("MainWindow", "새 캡처"))
        self.action_2.setText(_translate("MainWindow", "저장"))
        self.action_3.setText(_translate("MainWindow", "다른 이름으로 저장"))
        self.action_5.setText(_translate("MainWindow", "종료"))
        self.action_6.setText(_translate("MainWindow", "팀업 대화방선택"))
        self.action_7.setText(_translate("MainWindow", "실행취소"))
        self.action_8.setText(_translate("MainWindow", "다시실행"))
        self.action_9.setText(_translate("MainWindow", "복사"))
        self.action_I.setText(_translate("MainWindow", "잉크 색(I)"))
        self.action_R.setText(_translate("MainWindow", "지우개(R)"))
        self.action_Q.setText(_translate("MainWindow", "모든 잉크 지우기(Q)"))
        self.action_G.setText(_translate("MainWindow", "그림판으로 내보내기(G)"))
        self.action_13.setText(_translate("MainWindow", "선"))
        self.action_14.setText(_translate("MainWindow", "화살표"))
        self.action_15.setText(_translate("MainWindow", "사각형"))
        self.action_16.setText(_translate("MainWindow", "원"))
        self.action1pt.setText(_translate("MainWindow", "1pt"))
        self.action2pt.setText(_translate("MainWindow", "2pt"))
        self.action3pt.setText(_translate("MainWindow", "3pt"))
        self.action4pt.setText(_translate("MainWindow", "4pt"))
        self.action5pt.setText(_translate("MainWindow", "5pt"))
        self.action6pt.setText(_translate("MainWindow", "6pt"))
        self.action_17.setText(_translate("MainWindow", "팀업 로그인"))
        self.action_4.setText(_translate("MainWindow", "읽어보세요"))

import capture_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

